sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
install:
    - pip install coverage pytest "pytest-cov<2.6.0" flake8
    - pip install -r requirements.txt
script:
    - git rev-parse HEAD
    - py.test --cov=kanren -vv kanren
    - flake8 kanren
    - flake8 tests
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then
        pip install coveralls --use-mirrors;
        coveralls;
      fi
notifications:
  email: false
